spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create #주의 사용에 따라 create, update 사용 후 none으로 변경해주세요
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 100
#        show_sql: true   # 하이버네이트 기본 SQL 출력 옵션
#        format_sql: true # 하이버네이트 기본 SQL 포맷팅 옵션
#    show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_SERVER_URL}
    consumer:
      auto-offset-reset: latest
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: manual


logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSZ, Asia/Seoul} [%X{request_id}] %-5level [%thread] %logger{36} - %msg%n"
  file:
    name: /spring-log/application.log
